format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$c\
$cpp\
$java\
$rust\
$go\
$python\
$nodejs\
line_break\
$character"""

[fill]
symbol = ' '

[lua]
style='bold blue'
symbol = ''
format = 'via [$symbol ($version )]($style)'

[cpp]
style='sky blue'
symbol = ''
format = 'via [$symbol ($version )]($style)'

[c]
style='light teal'
symbol = ''
format = 'via [$symbol ($version )]($style)'

[rust]
symbol = "󱘗"
style = "bold red"
format = 'via [$symbol ($version)]($style)'

[java]
symbol = " "
format = "via [${symbol} ${version}](red)"

[python]
symbol = ""
style = "bold yellow"
format = 'via [$symbol ($version)]($style)'
